[build]
  command = "npm install && npm run build" # Change if using yarn or another package manager
  publish = "build"  # Change this to your actual build output folder (e.g., build, public, dist)

